# ankra_content_fingerprint: 061cf7e36d1d688a82084a8173b80a8dd091e6d71629ce10034f5c712d7759c5
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: beads
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:VWxCsOQ5uTuo5+7mJnntvM1/1w2h5zV676GCVODTZMjSq108vHi8KeE4b7goWtWVWsL2S88cXQtuObPXrNw5FMlPDmkJyW6bNtl+vFMjTg8bvjVGAAmxh3PdmL9juH3ezbfuGlUlem0=,iv:sRoQ0g4mUi9ZragrQ+/aNqF/RZJMEsJIS2w7V9I3VHc=,tag:hL+MLb+JRBz/zjVErU9uVw==,type:str]
sops:
    age:
        - recipient: age1k0ljt9v4nsvvdm4ur4494m64aa67try9klcu9wqnaydw3gfwq3jsx496al
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYai8wSGw2a1MrVTFVUnFX
            emVHZXpmM1ByNWFvM09tVHF3eE0zM3ZJSVJjClFnNGJaWnRxSWd3RXRsVlloZXdR
            REc1bEQ4RXlBd1dKYW1kNDJQUmhLNUkKLS0tIHd6Y0EvTjY2ZE12MHdJTlBlMFdT
            aWxBdGl6Z0h5KzlOVG1teHhYa0JjaUEKh15S+Iva6Pz1S+RNjt6Y/kIXVMCT9DjJ
            kG2TfPgRHnHPvQ9YefgjP5DDLSnobDcfxpnDWO3Bef5M770UrV7LnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T22:12:10Z"
    mac: ENC[AES256_GCM,data:7fZeRaZ2E7GPfyILnhfabUzL5HN13tkZpVIff7qsEZU0k+KO2OD7QW+/JeFIgwXO80Pv0PdnSQOw4BLXTGeHOREjB5aU4c/QBf9YEvSKEEyvk6vhKU6j/Pmm7Sb+hXJymfDYczYxLzhx3H5gDGtwgfz9h06QuavuyJgKYD5Byec=,iv:frSTdZeATgbcB9/7fy2a+8m/j3wW8bkjcpH/0iDHRp0=,tag:Tr0OMvHdCgqxDPibtmF2Hw==,type:str]
    encrypted_regex: ^(\.dockerconfigjson)$
    mac_only_encrypted: true
    version: 3.12.2
