# ankra_content_fingerprint: 988fc8fc03ea0b1b4c1aa1efed8263609997a12960afd41f1ec3a15875f930dd
# Source: beads-linear/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: beads-linear-session
    namespace: beads
    labels:
        app.kubernetes.io/name: beads-linear
        app.kubernetes.io/instance: beads-linear
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/version: 0.1.0
type: Opaque
stringData:
    sessionSecret: ENC[AES256_GCM,data:5weuNolgJatI9ZjrKW2HuC928QSq4OMAol4nlbsDlslPNyoTI0Quf022u1ImuGde,iv:jqPsX4YGGCvEkfpXjXdp37OMfmq5zEYCPRvzopMfzpI=,tag:hOOpeENWcSliPEvR0UT/cA==,type:str]
sops:
    age:
        - recipient: age1k0ljt9v4nsvvdm4ur4494m64aa67try9klcu9wqnaydw3gfwq3jsx496al
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a1B5Y04xeVhvZzYwUmpm
            T1FYT2dWRzBOWWVBVmVEdFJFd2w1Qjk1bWpRCk92c1FiQnhXR1BLRHZFSGoybnVq
            eWZuTjBzZ1IvN0ZSRzFXcjhtU1R6REUKLS0tIE5qR0FBU1gzOTFjSktQNHY4T2po
            MjZ5VEhFZi8vbjhiVXl2eVpqOFVlNlUKheuWO42DfR2kK1RG55t66syBe3JcH4f6
            /URTnx1qSo/8uOu5BD267qr15uCWkNoYtBFTy8V3AQoDuIVmLSlPoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-04T22:12:10Z"
    mac: ENC[AES256_GCM,data:bj4lgbkyS1AdJFq8is6TdP0EawwBTY73HMgoyUtMLEwoNkNR6UDApZ1b6W3zd/tSYNUnDsjCGqbsh0iLN40CZj3ml/WpJrbMpqjH4SVAbAf1/niU6rBcX18zX5Zb5+z/BGeNs/05v91qqBfPHCh2I3FcmNHWOz8y+7Tpnc+lbVY=,iv:sUatLwiCDFSin8K1ZkMWg8TkLFRhH0PgYtMZIaYEYLU=,tag:/ZzoAfMCeB576n1rNRGK8g==,type:str]
    encrypted_regex: ^(sessionSecret)$
    mac_only_encrypted: true
    version: 3.12.2
